# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ang_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ang(object):
    def setupUi(self, ang):
        ang.setObjectName("ang")
        ang.setEnabled(True)
        ang.resize(1024, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ang.sizePolicy().hasHeightForWidth())
        ang.setSizePolicy(sizePolicy)
        ang.setMinimumSize(QtCore.QSize(1024, 800))
        ang.setMaximumSize(QtCore.QSize(10240, 8000))
        self.centralwidget = QtWidgets.QWidget(ang)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(999999, 999999))
        self.centralwidget.setObjectName("centralwidget")
        ang.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ang)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        ang.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ang)
        self.statusbar.setObjectName("statusbar")
        ang.setStatusBar(self.statusbar)
        self.actionOpen_Star_File = QtWidgets.QAction(ang)
        self.actionOpen_Star_File.setObjectName("actionOpen_Star_File")
        self.actionFade = QtWidgets.QAction(ang)
        self.actionFade.setObjectName("actionFade")
        self.actionChoose_color = QtWidgets.QAction(ang)
        self.actionChoose_color.setObjectName("actionChoose_color")
        self.actionSet_Brush_Size = QtWidgets.QAction(ang)
        self.actionSet_Brush_Size.setObjectName("actionSet_Brush_Size")
        self.action10 = QtWidgets.QAction(ang)
        self.action10.setObjectName("action10")
        self.action30 = QtWidgets.QAction(ang)
        self.action30.setObjectName("action30")
        self.action50 = QtWidgets.QAction(ang)
        self.action50.setObjectName("action50")
        self.action70 = QtWidgets.QAction(ang)
        self.action70.setObjectName("action70")
        self.action90 = QtWidgets.QAction(ang)
        self.action90.setObjectName("action90")
        self.actionCustom = QtWidgets.QAction(ang)
        self.actionCustom.setObjectName("actionCustom")
        self.actionSave_Star_File = QtWidgets.QAction(ang)
        self.actionSave_Star_File.setObjectName("actionSave_Star_File")
        self.actionSet_Erase_Percent = QtWidgets.QAction(ang)
        self.actionSet_Erase_Percent.setObjectName("actionSet_Erase_Percent")
        self.menuFile.addAction(self.actionOpen_Star_File)
        self.menuFile.addAction(self.actionSave_Star_File)
        self.menuEdit.addAction(self.actionFade)
        self.menuSettings.addAction(self.actionChoose_color)
        self.menuSettings.addAction(self.actionSet_Brush_Size)
        self.menuSettings.addAction(self.actionSet_Erase_Percent)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(ang)
        QtCore.QMetaObject.connectSlotsByName(ang)

    def retranslateUi(self, ang):
        _translate = QtCore.QCoreApplication.translate
        ang.setWindowTitle(_translate("ang", "Ang"))
        self.menuFile.setTitle(_translate("ang", "File"))
        self.menuEdit.setTitle(_translate("ang", "Edit"))
        self.menuSettings.setTitle(_translate("ang", "Settings"))
        self.actionOpen_Star_File.setText(_translate("ang", "Open Star File"))
        self.actionFade.setText(_translate("ang", "Fade"))
        self.actionChoose_color.setText(_translate("ang", "Set Color"))
        self.actionSet_Brush_Size.setText(_translate("ang", "Set Brush Size"))
        self.action10.setText(_translate("ang", "10%"))
        self.action30.setText(_translate("ang", "30%"))
        self.action50.setText(_translate("ang", "50%"))
        self.action70.setText(_translate("ang", "70%"))
        self.action90.setText(_translate("ang", "90%"))
        self.actionCustom.setText(_translate("ang", "Custom"))
        self.actionSave_Star_File.setText(_translate("ang", "Save Star File"))
        self.actionSet_Erase_Percent.setText(_translate("ang", "Set Erase Percent"))

