# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_childwindow(object):
    def setupUi(self, childwindow):
        childwindow.setObjectName("childwindow")
        childwindow.resize(1875, 1202)
        childwindow.setMinimumSize(QtCore.QSize(1024, 800))
        childwindow.setMaximumSize(QtCore.QSize(99999, 99999))
        childwindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(childwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 1261, 102))
        self.layoutWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.layoutWidget.setObjectName("layoutWidget")
        self.menu_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.menu_layout.setContentsMargins(0, 0, 0, 0)
        self.menu_layout.setObjectName("menu_layout")
        self.log_text = QtWidgets.QTextBrowser(self.layoutWidget)
        self.log_text.setMaximumSize(QtCore.QSize(300, 100))
        self.log_text.setFocusPolicy(QtCore.Qt.NoFocus)
        self.log_text.setObjectName("log_text")
        self.menu_layout.addWidget(self.log_text)
        self.log_log = QtWidgets.QTextBrowser(self.layoutWidget)
        self.log_log.setMaximumSize(QtCore.QSize(500, 100))
        self.log_log.setFocusPolicy(QtCore.Qt.NoFocus)
        self.log_log.setObjectName("log_log")
        self.menu_layout.addWidget(self.log_log)
        self.but_clear = QtWidgets.QPushButton(self.layoutWidget)
        self.but_clear.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("ori1Uni")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.but_clear.setFont(font)
        self.but_clear.setFocusPolicy(QtCore.Qt.NoFocus)
        self.but_clear.setObjectName("but_clear")
        self.menu_layout.addWidget(self.but_clear)
        self.but_reload = QtWidgets.QPushButton(self.layoutWidget)
        self.but_reload.setMinimumSize(QtCore.QSize(100, 100))
        self.but_reload.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("ori1Uni")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.but_reload.setFont(font)
        self.but_reload.setFocusPolicy(QtCore.Qt.NoFocus)
        self.but_reload.setObjectName("but_reload")
        self.menu_layout.addWidget(self.but_reload)
        self.but_save = QtWidgets.QPushButton(self.layoutWidget)
        self.but_save.setMinimumSize(QtCore.QSize(100, 100))
        self.but_save.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("ori1Uni")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.but_save.setFont(font)
        self.but_save.setFocusPolicy(QtCore.Qt.NoFocus)
        self.but_save.setObjectName("but_save")
        self.menu_layout.addWidget(self.but_save)
        self.but_invert = QtWidgets.QPushButton(self.layoutWidget)
        self.but_invert.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("ori1Uni")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.but_invert.setFont(font)
        self.but_invert.setFocusPolicy(QtCore.Qt.NoFocus)
        self.but_invert.setObjectName("but_invert")
        self.menu_layout.addWidget(self.but_invert)
        self.log_cores = QtWidgets.QTextBrowser(self.layoutWidget)
        self.log_cores.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.log_cores.setFont(font)
        self.log_cores.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.log_cores.setReadOnly(False)
        self.log_cores.setObjectName("log_cores")
        self.menu_layout.addWidget(self.log_cores)
        self.log_sigma = QtWidgets.QTextBrowser(self.layoutWidget)
        self.log_sigma.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.log_sigma.setFont(font)
        self.log_sigma.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.log_sigma.setReadOnly(False)
        self.log_sigma.setObjectName("log_sigma")
        self.menu_layout.addWidget(self.log_sigma)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 100, 1781, 441))
        self.layoutWidget1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.windows_layout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.windows_layout.setContentsMargins(0, 0, 0, 0)
        self.windows_layout.setObjectName("windows_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ck_0 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ck_0.setFont(font)
        self.ck_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ck_0.setObjectName("ck_0")
        self.verticalLayout.addWidget(self.ck_0)
        self.graph_0 = QtWidgets.QGraphicsView(self.layoutWidget1)
        self.graph_0.setMaximumSize(QtCore.QSize(800, 600))
        self.graph_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graph_0.setObjectName("graph_0")
        self.verticalLayout.addWidget(self.graph_0)
        self.windows_layout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ck_1 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ck_1.setFont(font)
        self.ck_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ck_1.setObjectName("ck_1")
        self.verticalLayout_2.addWidget(self.ck_1)
        self.graph_1 = QtWidgets.QGraphicsView(self.layoutWidget1)
        self.graph_1.setMaximumSize(QtCore.QSize(800, 600))
        self.graph_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graph_1.setObjectName("graph_1")
        self.verticalLayout_2.addWidget(self.graph_1)
        self.windows_layout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ck_2 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ck_2.setFont(font)
        self.ck_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ck_2.setObjectName("ck_2")
        self.verticalLayout_3.addWidget(self.ck_2)
        self.graph_2 = QtWidgets.QGraphicsView(self.layoutWidget1)
        self.graph_2.setMaximumSize(QtCore.QSize(800, 600))
        self.graph_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graph_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.graph_2.setObjectName("graph_2")
        self.verticalLayout_3.addWidget(self.graph_2)
        self.windows_layout.addLayout(self.verticalLayout_3)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 540, 1781, 441))
        self.layoutWidget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ck_3 = QtWidgets.QCheckBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ck_3.setFont(font)
        self.ck_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ck_3.setObjectName("ck_3")
        self.verticalLayout_4.addWidget(self.ck_3)
        self.graph_3 = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.graph_3.setMaximumSize(QtCore.QSize(800, 600))
        self.graph_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graph_3.setObjectName("graph_3")
        self.verticalLayout_4.addWidget(self.graph_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ck_4 = QtWidgets.QCheckBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ck_4.setFont(font)
        self.ck_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ck_4.setObjectName("ck_4")
        self.verticalLayout_5.addWidget(self.ck_4)
        self.graph_4 = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.graph_4.setMaximumSize(QtCore.QSize(800, 600))
        self.graph_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graph_4.setObjectName("graph_4")
        self.verticalLayout_5.addWidget(self.graph_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ck_5 = QtWidgets.QCheckBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ck_5.setFont(font)
        self.ck_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ck_5.setObjectName("ck_5")
        self.verticalLayout_6.addWidget(self.ck_5)
        self.graph_5 = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.graph_5.setMaximumSize(QtCore.QSize(800, 600))
        self.graph_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graph_5.setObjectName("graph_5")
        self.verticalLayout_6.addWidget(self.graph_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(1550, 10, 241, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_readtype = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_readtype.setFont(font)
        self.label_readtype.setObjectName("label_readtype")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_readtype)
        self.combo_readtype = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.combo_readtype.setFont(font)
        self.combo_readtype.setObjectName("combo_readtype")
        self.combo_readtype.addItem("")
        self.combo_readtype.addItem("")
        self.combo_readtype.addItem("")
        self.combo_readtype.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_readtype)
        self.label_Page = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_Page.setFont(font)
        self.label_Page.setObjectName("label_Page")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Page)
        self.label_current_groupi = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_groupi.setFont(font)
        self.label_current_groupi.setObjectName("label_current_groupi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_current_groupi)
        self.Override = QtWidgets.QCheckBox(self.centralwidget)
        self.Override.setGeometry(QtCore.QRect(1340, 20, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Override.setFont(font)
        self.Override.setObjectName("Override")
        childwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(childwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1875, 37))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.menuOpen.setFont(font)
        self.menuOpen.setObjectName("menuOpen")
        childwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(childwindow)
        self.statusbar.setObjectName("statusbar")
        childwindow.setStatusBar(self.statusbar)
        self.actionSelect_From_Files = QtWidgets.QAction(childwindow)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.actionSelect_From_Files.setFont(font)
        self.actionSelect_From_Files.setObjectName("actionSelect_From_Files")
        self.actionSelect_From_Path = QtWidgets.QAction(childwindow)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.actionSelect_From_Path.setFont(font)
        self.actionSelect_From_Path.setObjectName("actionSelect_From_Path")
        self.menuOpen.addAction(self.actionSelect_From_Files)
        self.menuOpen.addAction(self.actionSelect_From_Path)
        self.menubar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(childwindow)
        QtCore.QMetaObject.connectSlotsByName(childwindow)

    def retranslateUi(self, childwindow):
        _translate = QtCore.QCoreApplication.translate
        childwindow.setWindowTitle(_translate("childwindow", "KDisplay"))
        self.but_clear.setText(_translate("childwindow", "clear"))
        self.but_reload.setText(_translate("childwindow", "reload"))
        self.but_save.setText(_translate("childwindow", "save"))
        self.but_invert.setText(_translate("childwindow", "invert"))
        self.log_cores.setHtml(_translate("childwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">32</p></body></html>"))
        self.log_sigma.setHtml(_translate("childwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.5</p></body></html>"))
        self.ck_0.setText(_translate("childwindow", "CheckBox"))
        self.ck_1.setText(_translate("childwindow", "CheckBox"))
        self.ck_2.setText(_translate("childwindow", "CheckBox"))
        self.ck_3.setText(_translate("childwindow", "CheckBox"))
        self.ck_4.setText(_translate("childwindow", "CheckBox"))
        self.ck_5.setText(_translate("childwindow", "CheckBox"))
        self.label_readtype.setText(_translate("childwindow", "readtype"))
        self.combo_readtype.setItemText(0, _translate("childwindow", "Unchecked"))
        self.combo_readtype.setItemText(1, _translate("childwindow", "Good"))
        self.combo_readtype.setItemText(2, _translate("childwindow", "Bad"))
        self.combo_readtype.setItemText(3, _translate("childwindow", "All"))
        self.label_Page.setText(_translate("childwindow", "Page"))
        self.label_current_groupi.setText(_translate("childwindow", "0/0"))
        self.Override.setText(_translate("childwindow", "Override"))
        self.menuOpen.setTitle(_translate("childwindow", "Open"))
        self.actionSelect_From_Files.setText(_translate("childwindow", "From Files"))
        self.actionSelect_From_Path.setText(_translate("childwindow", "From Path"))

